# Generated by Django 4.2.3 on 2023-07-25 15:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_authors_book_publisher_store_book_publisher'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('bl', django.db.models.manager.Manager()),
            ],
        ),
    ]
